CompuCompras/CompuCompras/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login_app.urls')),
    path('', include('store_app.urls')),
    path('', include('chat_app.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

CompuCompras/chat_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('chat/', views.chat, name='chat'),   
]

CompuCompras/store_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.get_productos, name='index'),
    path('nuevos', views.nuevos, name='nuevos'),
    path('ofertas/', views.ofertas, name='ofertas'),
    path('carrito/', views.get_carrito, name='carrito'),   
    path('agregar_al_carrito/', views.agregar, name='agregar'),
    path('eliminar_del_carrito/', views.eliminar, name='eliminar'),
    path('comprar/', views.comprar, name='comprar'),
]

CompuCompras/store_app/models.py
from django.db import models
from django.contrib.auth.models import User

class Producto(models.Model):
    titulo = models.CharField(max_length=100)
    descripcion = models.TextField()
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    categoria = models.CharField(max_length=100, default="Sin categoria")
    imagen = models.ImageField(upload_to="productos", null=True, blank=True)


    class Meta:
        verbose_name = 'Producto'
        verbose_name_plural = 'Productos'

    def __str__(self):
        return self.titulo
    
class Carrito(models.Model):
    productos = models.ManyToManyField(Producto, through='CarritoProducto')
    usuario = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    total = models.DecimalField(max_digits=10, decimal_places=2, null=True, default=0)
    
    cantidad_productos = models.IntegerField(default=0, null=True)
    def __str__(self):
        return str(self.productos)

class CarritoProducto(models.Model):
    carrito = models.ForeignKey(Carrito, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.IntegerField(default=0)

class Banner(models.Model):
    imagen = models.ImageField(upload_to="banners", null=True, blank=True)
    alt = models.CharField(max_length=100, null=True)
    

CompuCompras/store_app/views.py
from django.shortcuts import redirect, render, get_object_or_404
from .models import *
from django.contrib import messages
from django.contrib.auth.decorators import login_required
# Create your views here.


def ofertas(request):
    productos = Producto.objects.all()
    return render(request, 'ofertas.html',{'productos': productos})

def nuevos(request):
    productos = Producto.objects.all()
    return render(request, 'nuevos.html', {'productos': productos})

def get_productos(request):
    productos = Producto.objects.all()
    return render(request, 'index.html', {'productos': productos})


def agregar(request):
    id_producto = request.POST['producto_id']
    producto = Producto.objects.get(id=id_producto)
    carrito, creado = Carrito.objects.get_or_create(usuario=request.user)
    
    # Buscar si el producto ya está en el carrito
    item_carrito, creado_item = CarritoProducto.objects.get_or_create(carrito=carrito, producto=producto)
    
    # Incrementar la cantidad del producto en el carrito
    if not creado_item:
        item_carrito.cantidad += 1
        item_carrito.save()
    else:
        # Si se crea un nuevo item_carrito, establece la cantidad en 1
        item_carrito.cantidad = 1
        item_carrito.save()
    carrito.total += producto.precio
    carrito.cantidad_productos += 1
    carrito.save()
    messages.success(request, 'Añadido al carrito')
    return redirect(request.META.get('HTTP_REFERER', '/'))
    
@login_required
def get_carrito(request):
    carritos = Carrito.objects.filter(usuario=request.user).prefetch_related('productos')
    banners = Banner.objects.all()
    return render(request, 'carrito.html', {'carritos': carritos, 'banners': banners})



def eliminar(request):
    if request.method == 'POST':
        item_carrito_id = request.POST['item_carrito_id']
        item_carrito = get_object_or_404(CarritoProducto, id=item_carrito_id)
        
        cantidad_producto = item_carrito.cantidad
        precio_producto = item_carrito.producto.precio

        carrito = item_carrito.carrito
        
        carrito.total -= precio_producto
        
        if cantidad_producto > 1:
            item_carrito.cantidad -= 1
            carrito.cantidad_productos -= 1  
            item_carrito.save()
        else:
            item_carrito.delete()
            carrito.cantidad_productos -= 1  
        
        carrito.save()
        
        messages.success(request, 'Producto eliminado del carrito')
        return redirect(request.META.get('HTTP_REFERER', '/'))


def comprar(request):
    if request.method == 'POST':
        item_carrito_id = request.POST.get('item_carrito_id')
        carrito = get_object_or_404(Carrito, id=item_carrito_id)
        carrito.productos.clear()
        
        carrito.total = 0
        carrito.cantidad_productos = 0
        
        carrito.save()
        
        messages.success(request, 'Compra realizada')
        return redirect(request.META.get('HTTP_REFERER', '/'))

CompuCompras/store_app/templates/carrito.html
{% extends 'base_f.html' %}
{% block content %}

<div class="body-margin-start"></div>

<div class="informacion-compra">
    <div class="lista-productos">
        <p>{{carritos.cantidad_productos}}</p>
        {% for carrito in carritos %}
        {% for carrito_producto in carrito.carritoproducto_set.all %}

        <!-- Producto -->
        <div class="producto-item">
            <div class="img-producto-compra">
                <img class="imagen-pc-comprar" src="{{ carrito_producto.producto.imagen.url }}"
                    alt="{{ carrito_producto.producto.titulo }}">
            </div>
            <div class="info-producto-compra">
                <h3>{{ carrito_producto.producto.titulo }}</h3>
                <p>{{ carrito_producto.producto.descripcion }}</p>
                <p>Precio: ${{ carrito_producto.producto.precio }}</p>
                <p>Cantidad: {{ carrito_producto.cantidad }}</p>
            </div>
            <div class="btn-eliminar-div">
                <form action="{% url 'eliminar' %}" method="post" style="padding: 0%; border: 0cap;  background: none; display: flex; justify-content: center;">
                    {% csrf_token %}
                    <input type="hidden" name="item_carrito_id" value="{{ carrito_producto.id }}">
                    <button type="submit">Eliminar</button>
                </form>
                
            </div>
        </div>

        {% endfor %}
        {% endfor %}
    </div>

    <div class="total-compra">

        {% for carrito in carritos %}
        <p class="total-cantidad">Cantidad de artículos = {{ carrito.cantidad_productos }}</p>
        <p class="total-final">TOTAL: ${{carrito.total}}</p>
        {%if carrito.total != 0%}
        <div class="btn-comprar-div">
            

            <form id="btn-conf-compra" action="{% url 'comprar' %}" method="post" style="padding: 0%; border: 0cap;  background: none; display: flex; justify-content: center;">
                {% csrf_token %}
                <input type="hidden" name="item_carrito_id" value="{{ carrito.id }}">
                <button type="submit">Aceptar compra</button>
            </form>

        </div>
        {%endif%}
        {% endfor %}

    </div>
</div>


<section id="contacto">
    <h2>Contacto</h2>
    <p>Puedes contactarnos a través de nuestro correo electrónico <a
            href="mailto:ventas@computadoras.com">ventas@computadoras.com</a> o a través de nuestro número de teléfono
        555-555-5555.</p>
</section>

{% endblock %}

CompuCompras/store_app/templates/index.html
{%extends 'base_f.html'%}

{% block content %}
<!-- Boton Chat -->
<!-- 
<style>
	.message {
  font-size: 24px;
  padding: 10px;
  border-radius: 5px;
  right: 0px;
  font-family: 'Arial', sans-serif;
}

.authenticated {
  color: black; /* Verde oscuro */
  font-weight: bold;
}



</style> -->


<main>

	<div class="banner">
		<a href="https://www.example.com " target="_blank">
			<img id="carousel" src="" alt="">
		</a>
	</div>

	<h2>Computadoras destacadas</h2>

	<img src="{{ banners.imagen.url }}" alt="">

	{% if request.user.is_authenticated %}
	<p class="message authenticated">Bienvenido, {{ request.user.username }}</p>
	{% endif %}

	<section id="destacados" class="d-flex justify-content-around">
		{% if request.user.is_authenticated %}
		<div class="contenedor-bienvenida">
			<p class="mensaje-bienvenida">Bienvenido, {{ request.user.username }}</p>
		</div>
		{% endif %}
		<div class="cuadricula-de-computadoras">
			{%for computadora in productos%}
			{% if computadora.categoria == "destacada" %}
			<div class="computadora align-items-center">
				<img src="{{ computadora.imagen.url }}" alt="{{ computadora.titulo }}">
				<h3>{{computadora.titulo}}</h3>
				<p>{{computadora.descripcion}}</p>
				<p>Precio: ${{computadora.precio}}</p>

				{% if user.is_authenticated %}
				<form action="/agregar_al_carrito/" method="post"
					style="padding: 0%; border: 0cap;  background: none; display: flex; justify-content: center;">
					{% csrf_token %}
					<input type="hidden" name="producto_id" value="{{ computadora.id }}">
					<button type="submit">Añadir al carrito</button>
				</form>
				{% else %}
				<a href="{% url 'login' %}">
					<button type="submit">Añadir al carrito</button>
				</a>
				{% endif %}

			</div>
			{% endif %}
			{%endfor%}
		</div>
		

	</section>
	<section id="contacto">
		<h2>Contacto</h2>
		<p>Puedes contactarnos a través de nuestro correo electrónico <a
				href="mailto:ventas@computadoras.com">ventas@computadoras.com</a> o a través de nuestro número de
			teléfono 555-555-5555.</p>
	</section>
</main>



{% endblock %}

CompuCompras/store_app/templates/nuevos.html
{% extends 'base_f.html' %}
{% block content %}

<main>
	
	<h2>Novedades</h2>
    <section id="novedades" class="d-flex justify-content-around">
		<div class="cuadricula-de-computadoras">
			{%for computadora in productos%}
			{% if computadora.categoria == "novedades" %}
			<div class="computadora align-items-center">
				<img src="{{ computadora.imagen.url }}" alt="{{ computadora.titulo }}">
				<h3>{{computadora.titulo}}</h3>
				<p>{{computadora.descripcion}}</p>
				<p>Precio: ${{computadora.precio}}</p>
	
				{% if user.is_authenticated %}
				<form action="/agregar_al_carrito/" method="post"
					style="padding: 0%; border: 0cap;  background: none; display: flex; justify-content: center;">
					{% csrf_token %}
					<input type="hidden" name="producto_id" value="{{ computadora.id }}">
					<button type="submit">Añadir al carrito</button>
				</form>
				{% else %}
				<a href="{% url 'login' %}">
					<button type="submit">Añadir al carrito</button>
				</a>
				{% endif %}
	
			</div>
			{% endif %}
			{%endfor%}
			</div>
	
	</section>
    <section id="contacto">
		<h2>Contacto</h2>
		<p>Puedes contactarnos a través de nuestro correo electrónico <a href="mailto:ventas@computadoras.com">ventas@computadoras.com</a> o a través de nuestro número de teléfono 555-555-5555.</p>
	</section>
    </main>
{% endblock %}

CompuCompras/store_app/templates/ofertas.html
{% extends 'base_f.html' %}
{% block content %}

    <main>
		<h2>Ofertas especiales</h2>
        <section id="novedades" class="d-flex justify-content-around">
			<div class="cuadricula-de-computadoras">
				{%for computadora in productos%}
				{% if computadora.categoria == "ofertas" %}
				<div class="computadora align-items-center">
					<img src="{{ computadora.imagen.url }}" alt="{{ computadora.titulo }}">
					<h3>{{computadora.titulo}}</h3>
					<p>{{computadora.descripcion}}</p>
					<p>Precio: ${{computadora.precio}}</p>
		
					{% if user.is_authenticated %}
					<form action="/agregar_al_carrito/" method="post"
						style="padding: 0%; border: 0cap;  background: none; display: flex; justify-content: center;">
						{% csrf_token %}
						<input type="hidden" name="producto_id" value="{{ computadora.id }}">
						<button type="submit">Añadir al carrito</button>
					</form>
					{% else %}
					<a href="{% url 'login' %}">
						<button type="submit">Añadir al carrito</button>
					</a>
					{% endif %}
		
				</div>
				{% endif %}
				{%endfor%}
				</div>
		
		</section>
        <section id="contacto">
            <h2>Contacto</h2>
            <p>Puedes contactarnos a través de nuestro correo electrónico <a href="mailto:ventas@computadoras.com">ventas@computadoras.com</a> o a través de nuestro número de teléfono 555-555-5555.</p>
        </section>
    </main>
{% endblock %}